version: "3"
services:
  # labelstudio
  yolov8:
    image: yolov8
    build:
      context: .
      dockerfile: ./Dockerfile_simple
    volumes:
      - ./src:/usr/src
      - ./data:/data
    environment:
      TZ: "Asia/Tokyo"
      PYTHONDONTWRITEBYTECODE: 1
    command: tail -f /dev/null
